# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 16:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WashUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('isActivated', models.BooleanField()),
                ('status', models.SmallIntegerField(choices=[(1, 'enduser'), (3, 'exWaschag'), (5, 'waschag'), (7, 'admin'), (9, 'god')])),
            ],
            options={
                'db_table': 'washuser',
            },
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('isBonus', models.BooleanField()),
                ('wasUsed', models.BooleanField()),
            ],
            options={
                'db_table': 'appointments',
            },
        ),
        migrations.CreateModel(
            name='WashingMachines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(unique=True)),
                ('isAvailable', models.BooleanField()),
                ('notes', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'washingmachines',
            },
        ),
        migrations.CreateModel(
            name='WashParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'washparameters',
            },
        ),
        migrations.AddField(
            model_name='appointments',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wasch.WashingMachines'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
